# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cost', models.FloatField()),
                ('aqua', models.FloatField()),
                ('novel', models.FloatField()),
                ('leisure', models.FloatField()),
                ('coolShit', models.FloatField()),
                ('forest', models.FloatField()),
                ('mount', models.FloatField()),
                ('water', models.FloatField()),
                ('name', models.CharField(max_length=250)),
                ('yelp_rate', models.FloatField()),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='extendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cost', models.FloatField()),
                ('aqua', models.FloatField()),
                ('novel', models.FloatField()),
                ('leisure', models.FloatField()),
                ('coolShit', models.FloatField()),
                ('forest', models.FloatField()),
                ('mount', models.FloatField()),
                ('water', models.FloatField()),
                ('rate_counts', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
