# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='aqua',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='business',
            name='coolShit',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='business',
            name='cost',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='business',
            name='forest',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.FloatField(default=38.627),
        ),
        migrations.AlterField(
            model_name='business',
            name='leisure',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.FloatField(default=90.1994),
        ),
        migrations.AlterField(
            model_name='business',
            name='mount',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='business',
            name='novel',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='business',
            name='water',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='business',
            name='yelp_rate',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='aqua',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='coolShit',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='cost',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='forest',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='latitude',
            field=models.FloatField(default=38.627),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='leisure',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='longitude',
            field=models.FloatField(default=90.1994),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='mount',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='novel',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='rate_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='water',
            field=models.FloatField(default=0.01),
        ),
    ]
