# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='rate_counts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
