# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_graph', '0002_extendeduser_rate_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
